### ISSUE TITLE
Написать парсер для https://pinspb.ru

### ISSUE THREAD

**Issue by lebedev700** [ecodomen/nsreg-watcher#101]
Написать парсеры, которые собирают значения цены регистрации, продления и миграции и складывают их в БД в соответствии с [инструкцией](https://github.com/ecodomen/nsreg-watcher/blob/dev/%D0%A0%D0%A3%D0%9A%D0%9E%D0%92%D0%9E%D0%94%D0%A1%D0%A2%D0%92%D0%9E%20%D0%9D%D0%9E%D0%92%D0%98%D0%A7%D0%9A%D0%90.md) для:

https://pinspb.ru,

**Comment by Strzypo** [comment]
Принял сайт в работу

**Comment by poligrafo** [comment]
> Принял сайт в работу

пиши, если будут вопросы

**Comment by andrew097** [comment]
@Strzypo ты еще работаешь над этим? 
Если нет, я сделаю PR

**Comment by lebedev700** [comment]
@andrew097 привет! Если есть PR, можешь прицепить его к issue?

**Comment by andrew097** [comment]
@lebedev700 PR готов

**Comment by lebedev700** [comment]
Привет! Спасибо, посмотрим.

**Comment by lebedev700** [comment]
@andrew097 пришли, пожалуйста на почту info@ecodomen.ru удобный тебе способ связи и/или ник в ТГ.
