### ISSUE TITLE
Написать парсер для https://masterhost.ru

### ISSUE THREAD

**Issue by lebedev700** [ecodomen/nsreg-watcher#104]
Написать парсеры, которые собирают значения цены регистрации, продления и миграции и складывают их в БД в соответствии с [инструкцией](https://github.com/ecodomen/nsreg-watcher/blob/dev/%D0%A0%D0%A3%D0%9A%D0%9E%D0%92%D0%9E%D0%94%D0%A1%D0%A2%D0%92%D0%9E%20%D0%9D%D0%9E%D0%92%D0%98%D0%A7%D0%9A%D0%90.md) для:

https://masterhost.ru,

**Comment by MarselZ** [comment]
Добрый день.

Принял сайт в работу.

**Comment by lebedev700** [comment]
Нужно переписать

**Comment by rsolovyeaws** [comment]
цена на перенос бесплатная, но не парсится, всегда возвращается None.

https://masterhost.ru/domain/transfer/

**Comment by MarselZ** [comment]
Сделано.

**Comment by magrifat** [comment]
Здравствуйте! Набор в команду еще продолжается?

**Comment by lebedev700** [comment]
@MarselZ привет! Напиши, пожалуйста, на почту info@ecodomen.ru удобный способ связи или ник в ТГ.

**Comment by MarselZ** [comment]
@lebedev700 привет! Написал вчера.

**Comment by t1ooo** [comment]
https://github.com/ecodomen/nsreg-watcher/pull/245
