### ISSUE TITLE
Написать парсер для https://format.gtn.ee/home

### ISSUE THREAD

**Issue by lebedev700** [ecodomen/nsreg-watcher#113]
Написать парсеры, которые собирают значения цены регистрации, продления и миграции и складывают их в БД в соответствии с [инструкцией](https://github.com/ecodomen/nsreg-watcher/blob/dev/%D0%A0%D0%A3%D0%9A%D0%9E%D0%92%D0%9E%D0%94%D0%A1%D0%A2%D0%92%D0%9E%20%D0%9D%D0%9E%D0%92%D0%98%D0%A7%D0%9A%D0%90.md) для:

https://format.gtn.ee/home

**Comment by usbtypec1** [comment]
Принял сайт в работу

**Comment by poligrafo** [comment]
Если возникнут вопросы, то пиши, всегда поможем

**Comment by usbtypec1** [comment]
[Сайт](https://format.gtn.ee/price) отображает информацию о ценах, подгружая отдельный js файл. Что делать в этой ситуации? Парсить этот js файл напрямую?

<details>
<summary>Скрин</summary>
<img width="1440" alt="Screenshot 2023-12-17 at 11 01 39 PM" src="https://github.com/ecodomen/nsreg-watcher/assets/97338193/e8b0faff-c567-42f8-a68d-8704463bdd99">
</details>

**Comment by poligrafo** [comment]
не открывается их сайт пока, как заработает, то подскажу

**Comment by usbtypec1** [comment]
Я могу взять другой сайт в работу?

**Comment by SergeAvgust** [comment]
Да, если хочешь. Посмотри только, чтобы он был не занят)

**Comment by Danz1nger** [comment]
Сделано https://github.com/ecodomen/nsreg-watcher/pull/134/commits/09733221884e09482e92ea64ae2eafbe3df3bed8
