### ISSUE TITLE
Написать парсер для https://moskva.beeline.ru/business/domen/registratsiya-i-podderzhka-domenov/

### ISSUE THREAD

**Issue by lebedev700** [ecodomen/nsreg-watcher#114]
Написать парсеры, которые собирают значения цены регистрации, продления и миграции и складывают их в БД в соответствии с [инструкцией](https://github.com/ecodomen/nsreg-watcher/blob/dev/%D0%A0%D0%A3%D0%9A%D0%9E%D0%92%D0%9E%D0%94%D0%A1%D0%A2%D0%92%D0%9E%20%D0%9D%D0%9E%D0%92%D0%98%D0%A7%D0%9A%D0%90.md) для:

https://moskva.beeline.ru/business/domen/registratsiya-i-podderzhka-domenov/

**Comment by aleksey-vasilev** [comment]
На сайте есть только стоимость регистрации и какой-то прайс 2018 года: https://static.beeline.ru/upload/dpcupload/images/Tarify_Domeny_2018v.docx
