### ISSUE TITLE
Переписать парсер для https://2domains.ru

### ISSUE THREAD

**Issue by aleksey-vasilev** [ecodomen/nsreg-watcher#174]
Написать парсеры, которые собирают значения цены регистрации, продления и миграции и складывают их в БД в соответствии с [инструкцией](https://github.com/ecodomen/nsreg-watcher/blob/dev/%D0%A0%D0%A3%D0%9A%D0%9E%D0%92%D0%9E%D0%94%D0%A1%D0%A2%D0%92%D0%9E%20%D0%9D%D0%9E%D0%92%D0%98%D0%A7%D0%9A%D0%90.md)

**Comment by rsolovyeaws** [comment]
я его уже переписал. 
https://github.com/ecodomen/nsreg-watcher/pull/141/files
но не настроил линтер перед созданием пул реквеста. 
теперь исправил, чтобы линтер не ругался. подскажи как теперь поступить, закрыть тот пул реквест и создать новый?

**Comment by aleksey-vasilev** [comment]
Ты сделал хороший парсер, но такой вид спайдеров уже устарел
Мы поменяли структуру парсеров, пример можешь посмотреть в README.md(там целая инструкция).
Должно быть реализовано через BaseSpiderComponent.
И да, лучше сделать отдельным пул реквестом
