### ISSUE TITLE
Составить список парсеров для разработки

### ISSUE THREAD

**Issue by lebedev700** [ecodomen/nsreg-watcher#19]
1. Проанализировать какие не разработаны
2. Выдвинуть предложение, как сделать лучше
3. Сделать каждому участнику задачу со списком парсеров для разработки

**Comment by poligrafo** [comment]
Таблица с анализом парсеров - [тут](https://docs.google.com/spreadsheets/d/1GKl99sgEAIC0QZw1PQRD_ExORlXvA9XK55VswX0zg3g/edit)
