### ISSUE TITLE
Не отображается регитратор на сайте добавленный через панель администрирования в списке регистраторов

### ISSUE THREAD

**Issue by lebedev700** [ecodomen/nsreg-watcher#195]
#bug

Предусловия: Авторизоваться в панели администрирования Ecodomen по адресу https://ecodomen.ru/admin Добавить нового регистратора. Перейти на страницу https://ecodomen.ru

Шаги
1. Найти в списке регистраторов добавленный регистратор, через панель администрирования, не применяя поиск.

ФР: Регистратор добавленный через панель администрирования не отображается в списке без применения поиска
ОР: Регистратор добавленный через панель администрирования отображается в списке без применения поиска

**Comment by rsolovyeaws** [comment]
Посмотрю

**Comment by lebedev700** [comment]
Заассайнить Роберту

**Comment by rsolovyeaws** [comment]
Сделал, но #194 так же исправляет эту ошибку.
