### ISSUE TITLE
Сделать инструкцию развертывания на Linux

### ISSUE THREAD

**Issue by lebedev700** [ecodomen/nsreg-watcher#20]
https://github.com/ecodomen/nsreg-watcher/blob/main/DEV-DEPLOY.md

**Comment by StanislavOkopnyi** [comment]
https://github.com/ecodomen/nsreg-watcher/blob/dev/DEV-DEPLOY.md 
Сделано не через пулл реквест, т.к. dev был скопирован c dev-deployment

**Comment by aleksey-rezvov** [comment]
@mrezvova ждем результата ревью
