### ISSUE TITLE
Некорректный парсинг цен в мультиспайдерах

### ISSUE THREAD

**Issue by t1ooo** [ecodomen/nsreg-watcher#249]
## Шаги по воспроизведению
- запустить парсинг цен `bash runspiders.sh` несколько раз
- проверить результаты парсинга цен одного из регистраторов из мультиспайдров (multi_site_spider*.py) в админке

## Ожидаемый результат
Цены совпадают

## Фактический результат
Цены могут различаться

![1(1)](https://github.com/ecodomen/nsreg-watcher/assets/5966878/571d1dcc-ac95-44e2-87d0-6aad6d1c0437)
![2(1)](https://github.com/ecodomen/nsreg-watcher/assets/5966878/d1436c1f-c7c1-4b3e-9604-01db527595c8)
![3(1)](https://github.com/ecodomen/nsreg-watcher/assets/5966878/8bfe0382-6452-4b0a-ab54-a7dbedef2548)

**Comment by rsolovyeaws** [comment]
После изменения предложенного тобой в личке:
src/grabber/nsreg/settings.py

CONCURRENT_REQUESTS = 1

Спайдеры работают с той же скоростью, но цены корректные по всем спайдерам.
