### ISSUE TITLE
[Bug] При переходе в раздел "Команда" верстка в хедере ломается

### ISSUE THREAD

**Issue by lebedev700** [ecodomen/nsreg-watcher#262]
Предусловия:
1. Открыта страница https://ecodomen.ru/

Шаги:
1. Нажать на кнопку "Команда"

ФР: Кнопки перехода в разделы сайта "Проект" и "Команда" смещаются влево
ОР: Кнопки перехода в разделы сайта "Проект" и "Команда" не меняют положения при переходе в раздел "Команда"

![Image](https://github.com/ecodomen/nsreg-watcher/assets/139054470/dc6461ee-0f5b-4444-8c36-e86be763c117)

**Comment by kabanchick-spb** [comment]
Fixed

![Image](https://github.com/ecodomen/nsreg-watcher/assets/117968299/003eae51-7cc9-4416-9439-21c94e1db21b)
