### ISSUE TITLE
[Bug] Не соответствие стоимости продления регистратора "РЕГ.РУ"

### ISSUE THREAD

**Issue by ra3gon** [ecodomen/nsreg-watcher#263]
Открыта страница https://ecodomen.ru/

Шаги:

1. Выполнить поиск регистратора "РЕГ.РУ"
2. Сравнить стоимость продления выданные в поиске Ecodomen.ru с ценами указанными на сайте регистратора https://www.reg.ru/company/prices/#expanders=domain,cis

ФР: стоимость продления домена .RU не совпадает
ОР: стоимость продления домена .RU совпадают

![Image](https://github.com/ecodomen/nsreg-watcher/assets/139054470/c1e2896a-15b4-4800-a68b-b5a81a2d6d4e)

![Image](https://github.com/ecodomen/nsreg-watcher/assets/139054470/6d211eaa-3986-4369-acef-73a27dcd3914)

**Comment by t1ooo** [comment]
Ответ от поддержки reg.ru:

"В настоящее время стоимость регистрации доменов в зонах .RU и .РФ составляет 119 рублей, а стоимость продления на 1 год — 899 рублей при продлении из Личного кабинета https://www.reg.ru/domain/service/premium-renewal ."
