### ISSUE TITLE
[Bug] Не соответствие цены переноса домена, регистратор ООО «Бегет»

### ISSUE THREAD

**Issue by ra3gon** [ecodomen/nsreg-watcher#274]
Открыта страница https://ecodomen.ru/

Шаги:

1. Выполнить поиск регистратора "Регистратор Доменов"
2. Сравнить цену переноса домена выданные в поиске Ecodomen с ценой переноса  указанной на сайте регистратора https://beget.com/ru/kb/how-to/domains/kak-perenesti-domeny-v-beget#kak-perenesti-domen-ru-rf-k-registratoru-ooo-beget
ФР: цены переноса домена .RU не совпадает
ОР: цены переноса домена .RU совпадают

![Image](https://github.com/ecodomen/nsreg-watcher/assets/139054470/c6f46348-80f0-44e8-99ec-29e089014dcb)

**Comment by rsolovyeaws** [comment]
Бегет врубил защиту от парсинга. 

теперь приходит только:
```b"<html><head><script>function set_cookie(){var now = new Date();var time = now.getTime();time += 19360000 * 1000;now.setTime(time);document.cookie='beget=begetok'+'; expires='+now.toGMTString()+'; path=/';}set_cookie();location.reload();;</script></head><body></body></html>\n"```

теперь этот сайт проблемный
