### ISSUE TITLE
Ревью парсеров, рефактор по DRY

### ISSUE THREAD

**Issue by aleksey-rezvov** [ecodomen/nsreg-watcher#4]

**Comment by aleksey-rezvov** [comment]
до пятницы

**Comment by poligrafo** [comment]
Моё предложение по рефакторингу спайдеров [тут](https://github.com/ecodomen/nsreg-watcher/pull/29)

**Comment by SergeAvgust** [comment]
PR с предложением по рефактору спайдеров здесь: https://github.com/ecodomen/nsreg-watcher/pull/28

**Comment by lebedev700** [comment]
Решили сделать 2 варианта рефакторинга:
https://github.com/ecodomen/nsreg-watcher/issues/35 - через композицию
https://github.com/ecodomen/nsreg-watcher/issues/34 - через наследование
По результатам работы выберем лучший вариант.
