### ISSUE TITLE
Parse_History

### ISSUE THREAD

**Issue by lebedev700** [ecodomen/nsreg-watcher#60]
Создавать запись в таблицу цен при обновлении данных (т.е. дату и событие когда парсер отработал) (Insert)

**Comment by lebedev700** [comment]
https://github.com/ecodomen/nsreg-watcher/tree/feature-add-price-table

**Comment by poligrafo** [comment]
https://github.com/orgs/ecodomen/projects/1/views/1?pane=issue&itemId=33320585
