### ISSUE TITLE
Написать парсер для http://altnames.ru

### ISSUE THREAD

**Issue by lebedev700** [ecodomen/nsreg-watcher#82]
Написать парсеры, которые собирают значения цены регистрации, продления и миграции и складывают их в БД в соответствии с [инструкцией](https://github.com/ecodomen/nsreg-watcher/blob/dev/%D0%A0%D0%A3%D0%9A%D0%9E%D0%92%D0%9E%D0%94%D0%A1%D0%A2%D0%92%D0%9E%20%D0%9D%D0%9E%D0%92%D0%98%D0%A7%D0%9A%D0%90.md) для:

http://altnames.ru

**Comment by ekblb** [comment]
принято в работу

**Comment by lebedev700** [comment]
Парсер нужно переписать.
