### ISSUE TITLE
Написать парсер для https://domainer.ru/

### ISSUE THREAD

**Issue by lebedev700** [ecodomen/nsreg-watcher#84]
Написать парсеры, которые собирают значения цены регистрации, продления и миграции и складывают их в БД в соответствии с [инструкцией](https://github.com/ecodomen/nsreg-watcher/blob/dev/%D0%A0%D0%A3%D0%9A%D0%9E%D0%92%D0%9E%D0%94%D0%A1%D0%A2%D0%92%D0%9E%20%D0%9D%D0%9E%D0%92%D0%98%D0%A7%D0%9A%D0%90.md) для:

https://domainer.ru/,

**Comment by GalkinGry** [comment]
Взял в работу

**Comment by SergeAvgust** [comment]
Отлично, ждем твой пулл-реквест. Будут вопросы или проблемы - пиши)

**Comment by lebedev700** [comment]
Не дождались, нужно написать.
