### ISSUE TITLE
Написать парсер для http://personal-n.ru

### ISSUE THREAD

**Issue by lebedev700** [ecodomen/nsreg-watcher#89]
Написать парсеры, которые собирают значения цены регистрации, продления и миграции и складывают их в БД в соответствии с [инструкцией](https://github.com/ecodomen/nsreg-watcher/blob/dev/%D0%A0%D0%A3%D0%9A%D0%9E%D0%92%D0%9E%D0%94%D0%A1%D0%A2%D0%92%D0%9E%20%D0%9D%D0%9E%D0%92%D0%98%D0%A7%D0%9A%D0%90.md) для:

http://personal-n.ru,

**Comment by aleksey-vasilev** [comment]
На сайте есть только прайс с регистрацией и продлением от 2020 года: https://personal-n.ru/docs/registrar/Price-ru-rf-20102020.rtf
